config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "items#index"
  resources :items do
    member do
      post 'order'
      get 'done'
    end
    collection do
      get 'search'
      get 'divide'
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get 'like'
    end
  end
  resources :cards, only: [:new, :create, :show]
  resources :addresses
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :notifications, only: :index

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  with_options presence: true do
    validates :nickname
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date
  end
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, on: :create

  has_many :sns_credentials
  has_many :items
  has_one :card, dependent: :destroy
  has_many :orders
  has_one :address, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_one_attached :avatar
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :favorites
  has_many :favorite_items, through: :favorites, source: :item

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )

    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', nickname: 'ゲスト', family_name: '山田', first_name: '太郎', family_name_kana: 'ヤマダ', first_name_kana: 'タロウ', birth_date:'1990-01-01') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    resource.avatar.attach(account_update_params[:avatar]) if account_update_params[:avatar].present?
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(_resource)
    user_path(current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :like]
  before_action :set_address

  def index
    @items = current_user.items.page(params[:page]).per(4)
  end

  def show
    @nickname = current_user.nickname
    @items = @user.items.page(params[:page]).per(4)
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def like
    @favorite_items = @user.favorite_items.page(params[:page]).per(4)
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_address
    @address = current_user.address
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="mypage-wrap">
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main'>  
      <div class='form-header'>
        <h1 class='form-header-text'>
          プロフィール画像を変更する
        </h1>
      </div>
      <%= form_with model: @user, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">プロフィール写真</label>
        </div>
        <%= f.file_field :avatar %>
      </div>  
      <div class="update-btn">
        <%= f.submit "変更する", class:"register-red-btn" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="mypage-wrap">
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main' id="mypage-modal"> 
      <div class='form-header'>
        <h1 class='form-header-text'>
          出品一覧
        </h1>
      </div>
     <%= render "shared/pickup-list" %>
     <div class="pagination"><%= paginate @items %></div>
    </div>
  </div>
</div>

app/views/users/like.html.erb
<div class="mypage-wrap">
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main'>  
      <div class='form-header'>
        <h1 class='form-header-text'>
          お気に入りアイテム一覧
        </h1>
      </div>
      <div class="pickup-list">
        <ul>
          <% @favorite_items.each do |item| %>
            <li class="list">
              <%= link_to item_path(item.id) do %>
                <div class="item-img-content">
                  <%= image_tag item.image, class: "item-img" %>
                </div>
                <div class="item-info">
                  <div class="item-name">
                    <%= item.name %>
                  </div>
                  <div class="item-lower">
                    <div class="item-price">
                      <span>¥</span><%= item.price %><span class="stay">/1泊</span>
                    </div>
                    <div class="like-item" id="favorite-buttons<%= item.id %>">
                      <%= render partial: 'favorites/favorite', locals: { item: item } %>
                    </div>
                  </div>
                </div>
              <% end %>
            </li>
          <%end%>
        </ul>
      </div>
      <div class="pagination"><%= paginate @favorite_items %></div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="mypage-wrap">
<% if @user.id == current_user.id %>
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main' id="mypage-modal"> 
      <div class='form-header'>
        <h1 class='form-header-text'>
          マイページ
        </h1>
      </div>
      <div class="profile-avatar">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, class:'profile-image' %>
      <% else %>
        <img src='/images/profile_icon.png', class='profile-image' %>
      <% end %>
      </div>
      <div class="edit-btn">
        <%= link_to "変更する", edit_user_path(current_user.id), class:"edit-avatar-btn" %>
      </div>
      <div class='my-information'>
        <div class="my-information-group">
          <div class='my-text-wrap'>ニックネーム:</div>
          <div class="my-information-value"><%= @user.nickname %></div>
        </div>
        <div class="my-information-group">
          <div class='my-text-wrap'>お名前:</div>
          <div class="my-information-value"><%= @user.family_name %><%= @user.first_name %></div>
        </div>
        <div class="my-information-group">
          <div class='my-text-wrap'>お名前カナ:</div>
          <div class="my-information-value"><%= @user.family_name_kana %><%= @user.first_name_kana %></div>
        </div>
        <div class="my-information-group">
          <div class='my-text-wrap'>生年月日:</div>
          <div class="my-information-value"><%= @user.birth_date %></div>
        </div>
      </div>
    </div>
    <%= render "shared/item_list" %>
  </div>
<% else %>
  <div class="mypage-container">
    <div class='another-page-main'> 
      <div class='form-header'>
        <h1 class='form-header-text'>
          <%= @user.nickname + "さんのページ" %>
        </h1>
      </div>
      <div class="profile-avatar">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, class:'profile-image' %>
      <% else %>
        <img src='/images/profile_icon.png', class='profile-image' %>
      <% end %>
      </div>
      <div class="mypage-dm">
          <% if @isRoom == true %>
            <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="dm-btn">メッセージを送る</a>
          <% else %>
            <%= form_with model: @room, url: rooms_path, local: true do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "メッセージを送る", class:"dm-btn"%>
            <% end %>
          <% end %>
      </div>
      <div class="user-item">
      <h2>出品アイテム</h2>
      </div>
      <%= render 'shared/pickup-list' %>
      <div class="pagination"><%= paginate @items %></div>
    </div>
  </div>
<% end %>
</div>