config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "items#index"
  resources :items do
    member do
      post 'order'
      get 'done'
    end
    collection do
      get 'search'
      get 'divide'
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get 'like'
    end
  end
  resources :cards, only: [:new, :create, :show]
  resources :addresses
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :notifications, only: :index

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-content">
    <div><%= link_to 'CAMP BOX', root_path, class: "footer-title" %></div>
    <p class="footer-text">Copyright ©︎ 2020 CAMP BOX All rights reserved.</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-inner">
    <div class="header-seach">
      <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |f|%>
        <%= f.text_field :keyword, placeholder: "キャンプ用品名・キーワード", class: "search-input" %>
        <%= f.submit "検索する", class: "search-btn" %>
      <% end %>
    </div>
    <div class="clear"></div>
    <h1 class="logo"><%= link_to 'CAMP BOX', root_path, class: "logo-title" %></h1>
    <div class="header-menu">
      <ul class="lists-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id), class:"link-mypage" do%>
            <img src="/images/mypage.png" alt="人" class="mypage-icon">
            <span class="user-nickname">マイページ</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_item_path do%>
            <img src="/images/tent1.png" alt="テント" class="tent-icon">
            <span class="lend-item">出品する</span>
          <% end %>
        </li>
      <% end %>
        <span class="material-icons" id="open">menu</span>
      </ul>
    </div>
    <div class="overlay">
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete,  class: "login-icon" %></li>
            <li><%= link_to 'ヘルプ', "#", class: "login-icon" %></li>
          <% else %>
            <li class="login-icon" id="open-registration">会員登録</li>
            <li class="login-icon" id="open-session">ログイン</li>
            <li><%= link_to 'ヘルプ', "#", class: "login-icon" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_item_list.html.erb
<div class='mypage-main hidden' id="list-modal"> 
  <div class='form-header'>
    <h1 class='form-header-text'>
     出品一覧
    </h1>
  </div>
  <%= render 'shared/pickup-list' %>
</div>

app/views/shared/_mypage_side.html.erb
<div class="mypage-side">
      <nav class="mypage-nav">
        <ul class="mypage-nav-list">
          <li>
            <%= link_to user_path(current_user.id) do %>
            <div class="mypage-link">マイページ</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
            <div class="mypage-link">出品一覧</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          </li>
          <li>
            <%if unchecked_notifications.present?%>
              <%= link_to notifications_path do %>
              <div class="mypage-link">お知らせ</div>
              <img src="/images/bell.png" alt="logo" class="bell-image" >
              <span class="material-icons" id="mypage-icon">navigate_next</span>
              <% end %>
            <% else %>
              <%= link_to notifications_path do %>
              <div class="mypage-link">お知らせ</div>
              <span class="material-icons" id="mypage-icon">navigate_next</span>
              <% end %>
            <% end %>
          </li>
          <li>
            <%= link_to like_user_path(current_user.id) do %>
            <div class="mypage-link">お気に入り</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          </li>
          <li>
            <%= link_to rooms_path do %>
            <div class="mypage-link">メッセージ</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          </li>
          <li>
          <%if current_user.card.present? %>
            <%= link_to card_path(current_user.id) do %>
            <div class="mypage-link">クレジットカード</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          <% else %>
            <%= link_to new_card_path do %>
            <div class="mypage-link">クレジットカード</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          <% end %>
          </li>
          <li>
          <%if current_user.address.present? %>
            <%= link_to address_path(@address.id) do %>
            <div class="mypage-link">お届け先住所</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          <% else %>
            <%= link_to new_address_path do %>
            <div class="mypage-link">お届け先住所</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
            <div class="mypage-link">ログイン情報</div>
            <span class="material-icons" id="mypage-icon">navigate_next</span>
            <% end %>
          </li>
        </ul>
      </nav>
 </div>

app/views/shared/_pickup-list.html.erb
    <div class="pickup-list">
      <ul>
        <% @items.each do |item| %>
          <li class="list">
            <%= link_to item_path(item.id) do %>
              <div class="item-img-content">
                <%= image_tag item.image, class: "item-img" %>
              </div>
              <div class="item-info">
                <div class="item-name">
                  <%= item.name %>
                </div>
                <div class="item-lower">
                  <div class="item-price">
                    <span>¥</span><%= item.price %><span class="stay">/1泊</span>
                  </div>
                  <div class="like-item" id="favorite-buttons<%= item.id %>">
                    <%= render partial: 'favorites/favorite', locals: { item: item } %>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        <%end%>
      </ul>
    </div>

app/views/shared/_search_list.html.erb
<div class="pickup-list">
    <ul>
      <% @items.each do |item| %>
        <li class="search-list">
          <%= link_to item_path(item.id) do %>
            <div class="item-img-content">
              <%= image_tag item.image, class: "item-img" %>
            </div>
            <div class="item-info">
              <h2 class="item-name">
                <%= item.name %>
              </h2>
              <div class="item-lower">
                <div class="item-price">
                  <span>¥</span><%= item.price %><span class="stay">/1泊</span>
                </div>
                <div class="like-item" id="favorite-buttons<%= item.id %>">
                  <%= render partial: 'favorites/favorite', locals: { item: item } %>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <%end%>
    </ul>
  </div>

app/views/shared/_top_page.html.erb
<section class="main-visual">
  <img src="/images/camp-image.jpeg" class="main-image">

<section class="about">
  <div class="about-inner">
    <h2 class="about-title">
    CAMP BOX とは？
    </h2>
    <div class="about-image">
      <img src="/images/campbox.png" class="description-image">
    </div>
    <p class="about-text">
      「CAMP BOX」はキャンプ用品のシェアリングサービスです。<br>
      「キャンプ用品買ったけど、年に数回しか使わない。」<br>
      「キャンプに行きたいけど、キャンプ用品を揃えるにはお金がかかる。」<br>
      「買いたい商品を一度試してみたい。」<br>
      そんな悩みを一気に解決できるのが「CAMP BOX」です。<br>
      もっと気軽にキャンプを楽しめるサービスを実現します。
    </p>
  </div>
</section>


<div class="main-item">
  <div class="main-left">
    <div class="pickup">
      <h2>新着のアイテム</h2>
    </div>
    <%= render 'shared/pickup-list' %>
    <div class="pagination"><%= paginate @items %></div>
  </div>
  <div class="main-right">
    <div class="item-category">
      <h2>キャンプ用品一覧</h2>
      <ul>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=2' do %>
          <div class="category-link">テント</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=3' do %>
          <div class="category-link">タープ</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=4' do %>
          <div class="category-link">シェラフ・寝具</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=5' do %>
          <div class="category-link">テーブル</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=6' do %>
          <div class="category-link">チェア</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=7' do %>
          <div class="category-link">ランタン・照明器具</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=8' do %>
          <div class="category-link">調理道具</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=9' do %>
          <div class="category-link">暖房器具</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=10' do %>
          <div class="category-link">コット</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=11' do %>
          <div class="category-link">電化製品</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=12' do %>
          <div class="category-link">キャンプセット</div>
          <% end %>
        </li>
        <li class="category-list">
          <%= link_to '/items/divide?category_id=13' do %>
          <div class="category-link">その他</div>
          <% end %>
        </li>
      </ul>
    </div><br><br>
    <div class="item-category">
      <h2>おすすめのタグ</h2>
       <ul>
          <% @tags.each do |tag| %>
          <li class="category-list">
            <%= link_to tag, search_items_path(tag_name: tag.name), class: "category-link" %>
          </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>