config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "items#index"
  resources :items do
    member do
      post 'order'
      get 'done'
    end
    collection do
      get 'search'
      get 'divide'
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get 'like'
    end
  end
  resources :cards, only: [:new, :create, :show]
  resources :addresses
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :notifications, only: :index

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update]

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to address_path(@address.id)
    else
      render :edit
    end
  end

  private

  def address_params
    params.require(:address).permit(:post_code, :prefecture_id, :city, :house_number, :building_name, :phone_number).merge(user_id: current_user.id)
  end

  def set_address
    @address = Address.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/edit.html.erb
<div class="mypage-wrap">
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main'> 
      <div class='form-header'>
        <h1 class='form-header-text'>
          住所を変更する
        </h1>
      </div>
      <%= form_with model: @address, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
        <div class='form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">郵便番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :post_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">都道府県</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"address-prefecture"}) %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">市区町村</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）品川区"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">番地</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :house_number, class:"input-default", id:"addresses", placeholder:"例）品川1-1-1"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">建物名</label>
            <span class="undispensable">任意</span>
          </div>
          <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）品川ビル103"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">電話番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
        </div>
        <div class="update-btn">
          <%= f.submit "登録する", class:"register-red-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="mypage-wrap">
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main'> 
      <div class='form-header'>
        <h1 class='form-header-text'>
          住所を登録する
        </h1>
      </div>
      <%= form_with model: @address, url: addresses_path, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
        <div class='form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">郵便番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :post_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">都道府県</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"address-prefecture"}) %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">市区町村</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）品川区"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">番地</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :house_number, class:"input-default", id:"addresses", placeholder:"例）品川1-1-1"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">建物名</label>
            <span class="undispensable">任意</span>
          </div>
          <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）品川ビル103"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">電話番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
        </div>
        <div class="update-btn">
          <%= f.submit "登録する", class:"register-red-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/addresses/show.html.erb
<div class="mypage-wrap">
  <div class="mypage-container">
    <%= render "shared/mypage_side" %>
    <div class='mypage-main'> 
      <div class='form-header'>
        <h1 class='form-header-text'>
          お届け先住所
        </h1>
      </div>
        <div class="address-group">
          <div class='form-text-wrap'>
            <label class="form-text">住所</label>
          </div>
          <div class="address-value">〒<%= @address.post_code %><br><%= @address.prefecture.name %><%= @address.city %><%= @address.house_number %><%= @address.building_name %></div>
        </div>
        <div class="address-group">
          <div class='form-text-wrap'>
            <label class="form-text">電話番号</label>
          </div>
          <div class="address-value"><%= @address.phone_number %></div>
        </div>
        <div class="address-edit-btn">
          <%= link_to '変更する', edit_address_path(@address.id), method: :get, class: "address-red-btn" %>
        </div> 
    </div>
  </div>
</div>