config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "items#index"
  resources :items do
    member do
      post 'order'
      get 'done'
    end
    collection do
      get 'search'
      get 'divide'
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get 'like'
    end
  end
  resources :cards, only: [:new, :create, :show]
  resources :addresses
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :notifications, only: :index

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :order

  acts_as_taggable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :cost
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :category
  has_many :notifications, dependent: :destroy
  has_many :favorites

  with_options presence: true do
    validates :image
    validates :name
    validates :description
    validates :start_date
    validates :limit_date
    validates :price, format: { with: /\A[0-9]+\z/ }
  end
  validates :price, inclusion: { in: (500..100_000), message: 'に正しい値を入力してください' }
  validates :condition_id, :cost_id, :prefecture_id, :shipping_method_id, :category_id, numericality: { other_than: 1, message: 'を選択してください' }
  validate  :after_today

  def after_today
    errors.add(:start_date, 'は明日以降の日付を選択してください') if start_date < Date.today + 1
    errors.add(:limit_date, 'は開始日より後の日付を選択してください') if limit_date <= start_date
  end

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

  def self.divide(category_id)
    if search
      Item.where(category_id: category_id)
    else
      Item.all
    end
  end

  def create_notification_order(current_user, order_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Item.select(:user_id).where(item_id: id).distinct
    temp_ids.each do |temp_id|
      save_notification_order(current_user, order_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_order(current_user, order_id, user_id) if temp_ids.blank?
  end

  def save_notification_order(current_user, order_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.create(
      item_id: id,
      order_id: order_id,
      visited_id: visited_id,
      action: 'order'
    )
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :order]
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :move_to_session, only: [:new, :order]

  def index
    @user = User.new
    @items = Item.includes(:user).order('created_at DESC').page(params[:page]).per(4)
    @tags = Item.tag_counts_on(:tags).most_used(20)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @order = Order.new
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def order
    @order = Order.new(order_params)
    redirect_to new_card_path and return unless current_user.card.present?
    redirect_to new_address_path and return unless current_user.address.present?

    if @order.valid?
      pay_item
      @order.save
      @item.save_notification_order(current_user, @order.id, @item.user_id)
      render :done
    else
      render :order
    end
  end

  def done
    @order = Order.find(params[:id])
  end

  def search
    @items = Item.search(params[:keyword]).order('created_at DESC').page(params[:page]).per(8)
    @items = Item.tagged_with(params[:tag_name].to_s).order('created_at DESC').page(params[:page]).per(8) if params[:tag_name]
  end

  def divide
    @items = Item.where(category_id: params[:category_id]).order('created_at DESC').page(params[:page]).per(8)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :price, :description, :precaution, :condition_id, :cost_id, :prefecture_id, :shipping_method_id, :category_id, :start_date, :limit_date, :tag_list).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @item.user_id
  end

  def order_params
    params.require(:order).permit(:rental_start_date, :rental_limit_date).merge(item_id: params[:id], user_id: current_user.id)
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer_token = current_user.card.customer_token
    Payjp::Charge.create(
      amount: @item.price,
      customer: customer_token,
      currency: 'jpy'
    )
  end

  def move_to_session
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/divide.html.erb
<div class="search-item">
  <% if @items.present? %>
  <h1><%= @items[0].category.name%>一覧</h1>
  <% else %>
  <h1>現在そのカテゴリーのキャンプ用品はございません</h1>
  <% end %>
  <%= render 'shared/search_list' %>
  <div class="pagination"><%= paginate @items %></div>
</div>

app/views/items/done.html.erb
<div class="result-wrapper">
  <div id="mask"></div>
  <div class='form-wrap' id="date-select-modal">
    <div class='result-header'>
        以下の日程でレンタル申込が完了しました
    </div>
    <div class="rental-date-result">
      <%= @order.rental_start_date %> 〜 <%= @order.rental_limit_date %>
    </div>
    <div class="link_to_toppage">
      <%= link_to 'トップページへ戻る', root_path, class:"toppage"%>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="items-rental-contents">

  <div class="items-rental-main">
    <h2 class="items-rental-title">キャンプ用品の情報を編集する</h2>
    <%= form_with model: @item, local: true do |f| %>

    <br>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        写真
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">
        品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"キャンプ用品の説明（必須 1,000文字まで） 例）2018年頃に5万円で購入したテントです。5〜8人用なので、ファミリーでの使用におすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          注意事項
          <span class="undispensable">任意</span>
        </div>
        <%= f.text_area :precaution, class:"items-text", id:"item-info", placeholder:"キャンプ用品の注意事項（必須 1,000文字まで） 例）使用中に付着した汚れや水分などは、できるだけきれいに取り除いてからご返却ください" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="weight-bold-text">
        タグ
        <span class="undispensable">任意</span>
      </div>
      <%= f.text_field :tag_list, value: @item.tag_list.join(","), placeholder:" 例）初心者におすすめ, ソロキャンプ" ,class:"items-text" %>
    </div>

    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          配送方法
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_method_id, ShippingMethod.all, :id, :name, {}, {class:"select-box", id:"shipping-method"}) %>
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:cost_id, Cost.all, :id, :name, {}, {class:"select-box", id:"item-cost"}) %>
         <div class="weight-bold-text">
          レンタル可能期間
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_select :start_date, {}, class: 'rental-date' %>
        <span>〜</span>
        <%= f.date_select :limit_date, {}, class: 'rental-date' %>
         
      </div>
    </div>

    <div class="sell-price">
      <div>
        <div class="price-content">
          <div class="weight-bold-text">
            一泊あたりの価格(¥500〜100,000)
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        </div>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%# <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>

</div> 

app/views/items/index.html.erb
<div class='form-wrap hidden' id="select-modal">
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員登録
    </h1>
  </div>
  <ul class="sns-credential" id="email-registration">
    <li><img src="images/email.png" alt="logo" width="30px" height="30px"　align="middle"></li>
    <li class="sns-btn">メールアドレスで登録</li>
  </ul>
  <ul class="sns-credential">
    <li><img src="images/facebook.png" alt="logo" width="30px" height="30px"　align="middle"></li>
    <li><%= link_to 'Facebookで登録', user_facebook_omniauth_authorize_path, method: :post, class:"sns-btn"%></li>
  </ul>
  <ul class="sns-credential">
    <li><img src="images/google.png" alt="logo" width="30px" height="30px"　align="middle"></li>
    <li><%= link_to 'Googleで登録', user_google_oauth2_omniauth_authorize_path, method: :post, class:"sns-btn"%></li>
  </ul>
</div>


<div id="mask" class="hidden"></div>

<div class='form-wrap hidden' id="new-modal">
  <%= form_with model: @user, url: user_registration_path, class: 'registration-mains', local: true do |f| %>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>
  
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) camp太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <%if @sns_id.present? %>
  <%= hidden_field_tag :sns_auth, true %>
  <% else %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <% end %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">プロフィール写真</label>
      <span class="undispensable">任意</span>
    </div><br>
    <%= f.file_field :avatar %>
  </div><br>
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :family_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :family_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) タロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      登録すると、
      <span>利用規約</span>
      に同意したことになります。
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "会員登録" ,class:"register-red-btn" %>
  </div>
  <% end %>
</div>

<%= form_with model: @user, url: user_session_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap hidden' id="session-modal">
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>
  <div class='login-flash-message'>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"" %>
  </div>
  <div class='login-btn'>
    <%= f.submit "ログイン" ,class:"login-red-btn" %>
  </div>
  <div class="or">
  <span class="">or</span>
  </div>
  <ul class="sns-credential">
    <li><img src="images/facebook.png" alt="logo" width="30px" height="30px"　align="middle"></li>
    <li><%= link_to 'Facebookでログイン', user_facebook_omniauth_authorize_path, method: :post, class:"sns-btn"%></li>
  </ul>
  <ul class="sns-credential">
    <li><img src="images/google.png" alt="logo" width="30px" height="30px"　align="middle"></li>
    <li><%= link_to 'Googleでログイン', user_google_oauth2_omniauth_authorize_path, method: :post, class:"sns-btn"%></li>
  </ul>
  <ul class="guest-login">
    <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"guest-btn" %>
  </ul>
</div>
<% end %>

<%= render 'shared/top_page' %>

app/views/items/new.html.erb
<div class="items-rental-contents">

  <div class="items-rental-main">
    <h2 class="items-rental-title">キャンプ用品の情報を入力する</h2>
    <%= form_with model: @item, url: items_path,local: true do |f| %>

    <br>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        写真
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">
        品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"new-item-name", placeholder:"品名（必須 30文字まで)", maxlength:"30" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"キャンプ用品の説明（必須 1,000文字まで） 例）2018年頃に5万円で購入したテントです。5〜8人用なので、ファミリーでの使用におすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          注意事項
          <span class="undispensable">任意</span>
        </div>
        <%= f.text_area :precaution, class:"items-text", id:"item-info", placeholder:"キャンプ用品の注意事項（必須 1,000文字まで） 例）使用中に付着した汚れや水分などは、できるだけきれいに取り除いてからご返却ください" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="weight-bold-text">
        タグ
        <span class="undispensable">任意</span>
      </div>
      <%= f.text_field :tag_list, value: @item.tag_list.join(","), placeholder:" 例）初心者におすすめ, ソロキャンプ" ,class:"items-text" %>
    </div>

    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          配送方法
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_method_id, ShippingMethod.all, :id, :name, {}, {class:"select-box", id:"shipping-method"}) %>
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:cost_id, Cost.all, :id, :name, {}, {class:"select-box", id:"item-cost"}) %>
         <div class="weight-bold-text">
          レンタル可能期間
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_select :start_date, {}, class: 'rental-date' %>
        <span>〜</span>
        <%= f.date_select :limit_date, {}, class: 'rental-date' %>
         
      </div>
    </div>

    <div class="sell-price">
      <div>
        <div class="price-content">
          <div class="weight-bold-text">
            一泊あたりの価格(¥500〜100,000)
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        </div>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
    </div>

  </div>
  <% end %>

</div> 

app/views/items/order.html.erb
<div class="item-show-wrapper">
  <div class="item-show">
    <div class="item-image-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>
    <div class="item-detail-name">
      <%= @item.name %>
    </div>
    <div class="item-description">
      <div class="detail-header">キャンプ用品の説明</div>
      <p class="description-value"><%= @item.description %></p>
    <div class="item-detail-box">
      <div class="detail-header">詳細情報</div>
      <div class="item-detail">
        <div class="detail-title">価格(1泊)</div>
        <div class="detail-value">¥<%= @item.price %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">出品者</div>
        <div class="detail-value"><%= @item.user.nickname %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">カテゴリー</div>
        <div class="detail-value"><%= @item.category.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">状態</div>
        <div class="detail-value"><%= @item.condition.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">発送元の地域</div>
        <div class="detail-value"><%= @item.prefecture.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">配送方法</div>
        <div class="detail-value"><%= @item.shipping_method.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">配送料の負担</div>
        <div class="detail-value"><%= @item.cost.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">レンタル可能期間</div>
        <div class="detail-value"><%= @item.start_date %>〜<%= @item.limit_date %></div>
      </div>
          <div class="item-detail-precaution">
        <div class="detail-title">注意事項</div>
        <div class="detail-precaution-value"><%= @item.precaution %></div>
      </div>
    </div>
  </div>
</div>
<div class="rental-btn-contents">
  <% if user_signed_in? && current_user.id == @item.user_id %>
    <%= link_to '編集する', edit_item_path(@item.id), method: :get, class: "edit-item-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除する', item_path(@item.id), method: :delete, class:'destroy-item-btn' %>
  <% else %>
    <button type="button" id="rental-btn">
      <span>レンタルする</span>
    </button>
  <% end %>
</div>

<div id="mask"></div>

<div class='form-wrap' id="date-select-modal">
  <div class='date-header'>
    <h2 class='date-header-text'>
      希望の日付を選択してください
    </h2>
  </div>
  <%= form_with model: @order, url: order_item_path(@item.id), method: :post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    <div class="rental-date-select">
      <%= f.date_select :rental_start_date, {}, class: 'rental-date' %>
      <span>〜</span>
      <%= f.date_select :rental_limit_date, {}, class: 'rental-date' %>
    </div>

    <div class='rental-btn'>
      <%= f.submit "レンタルを確定する" ,class:"rental-red-btn" %>
    </div>
  <% end %>
</div>

app/views/items/search.html.erb
<div class="search-item">
  <h1>検索結果</h1>
  <%= render 'shared/search_list' %>
  <div class="pagination"><%= paginate @items %></div>
</div>

app/views/items/show.html.erb
<div class="item-show-wrapper">
  <div class="item-show">
    <div class="favorite-item" id="favorite-buttons<%= @item.id %>">
      <%= render partial: 'favorites/favorite', locals: { item: @item } %>
    </div>
    <div class="item-image-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>
    <div class="item-detail-name">
      <%= @item.name %>
    </div>
    <div class="item-description">
      <div class="detail-header">キャンプ用品の説明</div>
      <p class="description-value"><%= @item.description %></p>
    <div class="item-detail-box">
      <div class="detail-header">詳細情報</div>
      <div class="item-detail">
        <div class="detail-title">価格(1泊)</div>
        <div class="detail-value">¥<%= @item.price %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">出品者</div>
        <div class="detail-value"><%= link_to @item.user.nickname, user_path(@item.user_id) %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">カテゴリー</div>
        <div class="detail-value"><%= @item.category.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">タグ</div>
        <div class="detail-value">
          <% @item.tag_list.each do |tag| %>
            <%= link_to tag, search_items_path(tag_name: tag), class: "tag-text" %>
          <% end %>
        </div>
      </div>
      <div class="item-detail">
        <div class="detail-title">状態</div>
        <div class="detail-value"><%= @item.condition.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">発送元の地域</div>
        <div class="detail-value"><%= @item.prefecture.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">配送方法</div>
        <div class="detail-value"><%= @item.shipping_method.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">配送料の負担</div>
        <div class="detail-value"><%= @item.cost.name %></div>
      </div>
      <div class="item-detail">
        <div class="detail-title">レンタル可能期間</div>
        <div class="detail-value"><%= @item.start_date %>〜<%= @item.limit_date %></div>
      </div>
          <div class="item-detail-precaution">
        <div class="detail-title">注意事項</div>
        <div class="detail-precaution-value"><%= @item.precaution %></div>
      </div>
    </div>
  </div>
</div>
<div class="rental-btn-contents">
  <% if user_signed_in? && current_user.id == @item.user_id %>
    <%= link_to '編集する', edit_item_path(@item.id), method: :get, class: "edit-item-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除する', item_path(@item.id), method: :delete, class:'destroy-item-btn' %>
  <% else %>
    <button type="button" id="rental-btn">
      <span>レンタルする</span>
    </button>
  <% end %>
</div>

<div id="mask" class="hidden"></div>

<div class='form-wrap hidden' id="date-select-modal">
  <div class='date-header'>
    <h2 class='date-header-text'>
      希望の日付を選択してください
    </h2>
  </div>
  <%= form_with model: @order, url: order_item_path(@item.id), method: :post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    <div class="rental-date-select">
      <%= f.date_select :rental_start_date, {}, class: 'rental-date' %>
      <span>〜</span>
      <%= f.date_select :rental_limit_date, {}, class: 'rental-date' %>
    </div>

    <div class='rental-btn'>
      <%= f.submit "レンタルを確定する" ,class:"rental-red-btn" %>
    </div>
  <% end %>
</div>